[project]
name = "mcp-server-time"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=2.10.1",
    "mcp[cli]>=1.10.1",
]
